[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [
    { access = "read", path = "./lido-core/deployed-local.json"},
    { access = "read-write", path = "./artifacts" },
    { access = "read", path = "./" },
    { access = "read-write", path = "./deployments" }
]
solc_version = "0.8.30"
via_ir = true # although it's slower it helps with stack too deep errors in tests
dynamic_test_linking = true # to improve compilation speed

optimizer = true
optimizer_runs = 200

# Remappings
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "forge-std/=lib/forge-std/src/",
    "@solmate/=boring-vault/lib/solmate/src/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[fmt]
# Commonly used, readable defaults
line_length = 120
tab_width = 4
bracket_spacing = false
int_types = "long"            # prefer uint256/int256 over uint/int
quote_style = "double"
sort_imports = true
multiline_func_header = "attributes_first"
number_underscore = "preserve"
wrap_comments = false
single_line_statement_blocks = "preserve"

ignore = [
    "lib/**",
    "out/**",
    "lido-core/**",
    "test/**",
    "script/**",
]

[lint]
lint_on_build = true
exclude_lints = ["mixed-case-variable", "mixed-case-function", "pascal-case-struct", "unsafe-cheatcode"]
