[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [
    { access = "read", path = "./lido-core/deployed-local.json"},
    { access = "read-write", path = "./artifacts" }
]
solc_version = "0.8.30"
via_ir = true # although it's slower it helps with stack too deep errors in tests
dynamic_test_linking = true # to improve compilation speed

optimizer = false # disabled during active development to improve compilation speed
optimizer_runs = 200

# Remappings
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "forge-std/=lib/forge-std/src/",
    "@solmate/=boring-vault/lib/solmate/src/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
