[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read", path = "./lido-core/deployed-local.json"}]
solc_version = "0.8.30"
via_ir = true # although it's slower it helps with stack too deep errors in tests
dynamic_test_linking = true # to improve compilation speed

optimizer = false # disabled during active development to improve compilation speed
optimizer_runs = 200

# Remappings
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "core/=../core/",
    "forge-std/=lib/forge-std/src/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
