[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read", path = "./lido-core/deployed-local.json"}]
solc_version = "0.8.25"
# via_ir = true # don't use at least to build faster
optimizer = true
optimizer_runs = 200

# Remappings
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "core/=../core/",
    "forge-std/=lib/forge-std/src/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
