name: Common setup
description: Prepare foundry and repo deps

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Foundry
      uses: foundry-rs/foundry-toolchain@v1

    - name: Install Foundry dependencies
      shell: bash
      run: forge install

    - name: Build contracts
      shell: bash
      run: forge build
