name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: foundry-rs/foundry-toolchain@v1
      - run: forge fmt --check

  build:
    name: Build & Check Sizes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: foundry-rs/foundry-toolchain@v1
      - run: forge build --sizes

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: ./.github/actions/setup
      - run: just test-unit

  integration-hoodi:
    name: Integration Tests (Hoodi)
    runs-on: ubuntu-latest
    needs: build
    timeout-minutes: 10
    env:
      FOUNDRY_PROFILE: test
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: ./.github/actions/setup
      - run: just -E .env.hoodi.local test-integration

  integration-scratch:
    name: Integration Tests (Scratch)
    runs-on: ubuntu-latest
    needs: build
    timeout-minutes: 15
    env:
      FOUNDRY_PROFILE: test
    services:
      anvil:
        image: ghcr.io/lidofinance/hardhat-node:2.26.0-scratch
        ports:
          - 9123:8545
        env:
          HARDFORK: prague
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: ./.github/actions/setup
      - name: Setup Lido Core
        run: |
          just core-init feat/vaults
          just core-deploy lido-core 9123
      - name: Deploy GGV mocks
        run: just -E .env.local deploy-ggv-mocks
      - run: just -E .env.local test-integration

  deploy-hoodi-fork:
    name: Deploy (Hoodi Fork)
    runs-on: ubuntu-latest
    needs: build
    timeout-minutes: 10
    services:
      anvil:
        image: ghcr.io/lidofinance/hardhat-node:2.26.0
        ports:
          - 9123:8545
        env:
          ETH_RPC_URL: https://hoodi.drpc.org
          DONT_SET_CHAIN_ID: true
          HARDFORK: prague
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: ./.github/actions/setup
      - run: just -E .env.hoodi.local deploy-all .env.hoodi.local
