name: Integrations On Scratch Core

on:
  push:
  workflow_dispatch:

jobs:
  test_integration:
    name: Integration Tests On Scratch Core
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      FOUNDRY_PROFILE: test

    services:
      hardhat-node:
        image: ghcr.io/lidofinance/hardhat-node:2.26.0-scratch
        env:
          HARDFORK: "prague"
        ports:
          - 9123:8545

    steps:
      - uses: actions/checkout@v4

      - name: Just setup
        uses: ./.github/actions/just

      - name: Common setup
        uses: ./.github/workflows/setup

      - name: Initialize Lido Core
        run: just -E .env.local core-init feat/vaults

      - name: Deploy Lido Core
        run: just -E .env.local core-deploy lido-core 9123

      - name: Deploy GGV mocks
        run: just -E .env.local deploy-ggv-mocks

      - name: Run integration tests
        run: just E .env.local test-integration
