name: Integrations On Hoodi Core

on:
  push:
  workflow_dispatch:

jobs:
  test_integration:
    name: Integration Tests On Hoodi Core
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      FOUNDRY_PROFILE: test
      RPC_URL: "https://hoodi.drpc.org"
      CORE_LOCATOR_ADDRESS: "0xe2EF9536DAAAEBFf5b1c130957AB3E80056b06D8"

    steps:
      - uses: actions/checkout@v4

      - name: Common setup
        uses: ./.github/workflows/setup

      - name: Run integration tests for StvPool
        run: make test-integration-a

      - name: Run integration tests for StvStETHPool
        run: make test-integration-b

      - name: Run integration tests for GGV
        run: make test-integration-ggv
