name: Unit Tests

on:
  push:
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Just setup
        uses: ./.github/actions/just

      - name: Common setup
        uses: ./.github/workflows/setup

      - name: Run Forge tests
        env:
          RPC_URL: "not used actually but required"
        run: |
          just test-unit
        id: test
